### ISSUE TITLE
openmc xml file written by convertPyneMatLib.py is missing header and footer

### ISSUE THREAD

**Issue by Edgar-21** [svalinn/fusion-material-db#7]

**Comment by gonuke** [comment]
Is this still a problem @Edgar-21 ?  If so, can you post a minimal example demonstrating the failure?

**Comment by Edgar-21** [comment]
yes this is still an issue, generally speaking I think convertPyneMatLib could use a bit of an overhaul. I'll make another issue to that effect and take a look at it. Its a one line change to fix the openmc issue, but it would be nice to get the convert tool working consistently with the new directory structure.
