### ISSUE TITLE
refactor mixPureFusionMaterials.py to reduce repeated code

### ISSUE THREAD

**Issue by Edgar-21** [svalinn/fusion-material-db#9]
`mixPureFusionMaterials.py` has many functions with nearly identical structure that are hand-coded to produce different materials.  A better approach would be to have a dictionary such as:
```
mixMatData = { 'mixMatName' :  mats : { 'mat1' : vol_frac1, 'mat2' : vol_frac2, ...},  citation: 'mixture citation' }
```
and then a single function that converts this data to a mixture
```
def make_mixture(material_lib, mats, citation):
```

that processes the info in `mixMatData` and returns a material object, and then call all of that in `main` as:

```
for mixname, mixdata in mixMatData.items():
    mixlib[mixnname] = make_mixture(matLib, mixdata[mats], mixdata[citation])
```

or something like that

**Comment by Edgar-21** [comment]
see #6

**Comment by gonuke** [comment]
Completed by #15
